/* Applies every Android-side edit a Capacitor game project needs.
   Called by build-android.sh with: <projectDir> <slug> <appName> <appId> <versionName> <versionCode> */
import fs from 'node:fs';
import path from 'node:path';

const [proj, slug, appName, appId, versionName, versionCode, admobAppId] = process.argv.slice(2);
const ROOT = path.resolve(new URL('..', import.meta.url).pathname);
const A = path.join(proj, 'android');
const res = path.join(A, 'app/src/main/res');

const rd = f => fs.readFileSync(f, 'utf8');
const wr = (f, s) => { fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, s); };
const say = m => console.log('   ' + m);

/* ---- 1. strings.xml: app name + the AdMob application id ---------------- */
{
  const f = path.join(res, 'values/strings.xml');
  wr(f, `<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">${appName}</string>
    <string name="title_activity_main">${appName}</string>
    <string name="package_name">${appId}</string>
    <string name="custom_url_scheme">${appId}</string>

    <!-- ===================================================================
         GENERATED. Do not edit this file — the build rewrites it every run.
         Set admobAppId in app.config.json instead.
         =================================================================== -->
    <string name="admob_app_id">${admobAppId}</string>
</resources>
`);
  say('strings.xml — app name + admob_app_id placeholder');
}

/* ---- 2. AndroidManifest: portrait lock, AdMob meta-data, hardware accel -- */
{
  const f = path.join(A, 'app/src/main/AndroidManifest.xml');
  let x = rd(f);

  if (!/screenOrientation/.test(x)) {
    x = x.replace(/(<activity\b[^>]*?)(>)/, '$1\n            android:screenOrientation="portrait"$2');
  }
  if (!/com\.google\.android\.gms\.ads\.APPLICATION_ID/.test(x)) {
    x = x.replace(/\n(\s*)<\/application>/, (m, ind) =>
      '\n' + ind + '    <!-- Google Mobile Ads: the id itself lives in res/values/strings.xml -->\n' +
      ind + '    <meta-data\n' +
      ind + '        android:name="com.google.android.gms.ads.APPLICATION_ID"\n' +
      ind + '        android:value="@string/admob_app_id" />\n\n' +
      ind + '    <!-- Ads start loading sooner if the SDK may warm up early -->\n' +
      ind + '    <meta-data\n' +
      ind + '        android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION"\n' +
      ind + '        android:value="true" />\n' +
      ind + '    <meta-data\n' +
      ind + '        android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING"\n' +
      ind + '        android:value="true" />\n' +
      ind + '</application>');
  }
  // The GMA SDK adds the AD_ID permission itself. Declaring it here too keeps
  // the Play "Data safety" answer and the manifest honest and visible.
  if (!/permission\.AD_ID/.test(x)) {
    x = x.replace(/(<uses-permission android:name="android.permission.INTERNET" \/>)/,
      '$1\n    <uses-permission android:name="com.google.android.gms.permission.AD_ID" />');
  }
  wr(f, x);
  say('AndroidManifest.xml — portrait, AdMob app id, AD_ID permission');
}

/* ---- 3. variables.gradle: SDK levels Play requires ---------------------- */
{
  const f = path.join(A, 'variables.gradle');
  if (fs.existsSync(f)) {
    let g = rd(f);
    // Play: from 31 Aug 2026 new apps and updates must target Android 16 (36).
    g = g.replace(/minSdkVersion = \d+/, 'minSdkVersion = 23')
         .replace(/compileSdkVersion = \d+/, 'compileSdkVersion = 36')
         .replace(/targetSdkVersion = \d+/, 'targetSdkVersion = 36');
    wr(f, g);
    say('variables.gradle — minSdk 23, compile/target SDK 36');
  }
}

/* ---- 4. app/build.gradle: version name + code -------------------------- */
{
  const f = path.join(A, 'app/build.gradle');
  let g = rd(f);
  g = g.replace(/versionCode \d+/, 'versionCode ' + versionCode)
       .replace(/versionName "[^"]*"/, `versionName "${versionName}"`);
  wr(f, g);
  say(`app/build.gradle — versionName ${versionName}, versionCode ${versionCode}`);
}

/* ---- 5. launcher icons (legacy + adaptive) ----------------------------- */
{
  const src = path.join(ROOT, 'store-assets', slug, 'android-res');
  let n = 0;
  for (const d of fs.readdirSync(src)) {
    const from = path.join(src, d), to = path.join(res, d);
    fs.mkdirSync(to, { recursive: true });
    for (const f of fs.readdirSync(from)) { fs.copyFileSync(path.join(from, f), path.join(to, f)); n++; }
  }
  // adaptive icon descriptors (Android 8+)
  const ad = `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>
`;
  wr(path.join(res, 'mipmap-anydpi-v26/ic_launcher.xml'), ad);
  wr(path.join(res, 'mipmap-anydpi-v26/ic_launcher_round.xml'), ad);
  say(`launcher icons — ${n} PNGs + adaptive icon XML`);
}

/* ---- 6. splash / launch theme colour ----------------------------------- */
{
  wr(path.join(res, 'values/colors.xml'), `<?xml version='1.0' encoding='utf-8'?>
<resources>
    <color name="colorPrimary">#080b14</color>
    <color name="colorPrimaryDark">#080b14</color>
    <color name="colorAccent">#4ee1c1</color>
    <!-- NB: ic_launcher_background is already defined by Capacitor in
         res/values/ic_launcher_background.xml. Defining it again here is a
         duplicate value resource and AAPT2 refuses to link. The adaptive
         icon uses @mipmap/ic_launcher_background (a PNG) anyway. -->
</resources>
`);
  const st = path.join(res, 'values/styles.xml');
  if (fs.existsSync(st)) {
    let s = rd(st);
    if (!/windowBackground/.test(s)) {
      s = s.replace(/(<style name="AppTheme\.NoActionBar(?:Launch)?"[^>]*>)/g,
        '$1\n        <item name="android:windowBackground">@color/colorPrimary</item>');
    }
    wr(st, s);
  }
  say('colors.xml + launch background — no white flash on cold start');
}

/* ---- 6b. splash screen: brand colour + centred emblem ------------------ */
{
  // Capacitor ships a generic splash.png per density. Replace the whole set
  // with one vector-ish layer-list so the cold-start screen is on-brand and
  // weighs nothing.
  let removed = 0;
  for (const d of fs.readdirSync(res)) {
    if (!d.startsWith('drawable')) continue;
    const f = path.join(res, d, 'splash.png');
    if (fs.existsSync(f)) { fs.unlinkSync(f); removed++; }
  }
  wr(path.join(res, 'drawable/splash.xml'), `<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/colorPrimary" />
    <item
        android:gravity="center"
        android:width="180dp"
        android:height="180dp">
        <bitmap
            android:gravity="center"
            android:src="@mipmap/ic_launcher_foreground" />
    </item>
</layer-list>
`);
  say(`splash — ${removed} stock PNGs replaced by an on-brand layer-list`);
}

/* ---- 6c. release signing wired to keystore.properties ------------------ */
{
  const f = path.join(A, 'app/build.gradle');
  let g = rd(f);
  if (!/keystorePropertiesFile/.test(g)) {
    g = `def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

` + g;
    // signingConfigs must come before buildTypes inside android { }
    g = g.replace(/(\n\s*)buildTypes \{/, `$1signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }$1buildTypes {`);
    g = g.replace(/(buildTypes \{\s*\n\s*release \{)/,
      `$1
            if (keystorePropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }`);
    wr(f, g);
    say('app/build.gradle — release signing reads keystore.properties when present');
  }
}

/* ---- 7. release signing stub ------------------------------------------- */
{
  const f = path.join(A, 'keystore.properties.example');
  wr(f, `# Copy to keystore.properties (which is git-ignored) and fill in.
# Generate the keystore once and NEVER lose it — Play ties your app's
# identity to it forever unless you enrol in Play App Signing.
#
#   keytool -genkey -v -keystore upload-keystore.jks \\
#     -keyalg RSA -keysize 2048 -validity 10000 -alias upload
#
storeFile=../upload-keystore.jks
storePassword=CHANGE_ME
keyAlias=upload
keyPassword=CHANGE_ME
`);
  say('keystore.properties.example — signing template');
}

console.log(`   done: ${appName} (${appId})`);
